#!/usr/bin/env python
import vcf
import csv
import fileinput
import re
import argparse

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('genelist', nargs="+")
    parser.add_argument('--vcf', type=argparse.FileType('r'), required=True)
    args = parser.parse_args()
    delim = ","
    genes=fileinput.FileInput(args.genelist)
    genereader=csv.reader(genes, delimiter=delim)
    x=[]
    for line in genereader:
    	x=x+line
    genelist=set(x)
    reader = csv.reader(args.vcf, delimiter=delim)
    genefinder(reader, genelist,delim)


def genefinder(varlist,geneset,delimet):
	for line in varlist:
		for word in geneset:
			if word in re.split(', |\(|\)',line[1]):
				print delimet.join(line) 
				break

if __name__ == '__main__':
    main()
